### ISSUE TITLE
tail -r does not exists anymore

### ISSUE THREAD

**Issue by brnrd** [dreamyguy/gitlogg#1]
In some newer distributions, the option -r to reverse the output does not exist anymore.

It can be solved by using the command `tac` instead of `tail -r`

Edit: Actually you can get the log in reverse order by using the `--reverse` option for the `git log` command.

**Comment by dreamyguy** [comment]
Hi @brnrd, cheers for pointing this out!

I'm finally breathing some life into this project again, and plan to do many improvements. The https://github.com/dreamyguy/gitlogg/tree/v0.1.1 release was a major improvement in all the ways that matter, but I just realised `tail -r` is still there.

I'll be looking into this, and will probably follow your lead on the `--reverse`. Either that or you can [add it to this line](https://github.com/dreamyguy/gitlogg/blob/11a50b23e63aee9e725d795c16aaf0893f0bfaba/gitlogg/gitlogg-generate-log.sh#L28) and make a pull-request, which I'll gladly accept. 🏆  ✨

**Comment by dreamyguy** [comment]
It was such a straight-forward fix, so I just did it while I was at it.

Cheers for pointing it out! @brnrd++
