### ISSUE TITLE
Refactor gitlogg.sh

### ISSUE THREAD

**Issue by Inventitech** [dreamyguy/gitlogg#14]
I have two ideas to improve gitlogg's code quality (bash part):

- gitlogg.sh is just a forwarder to gitlogg-generate-log.sh. Why not get rid of gitlogg.sh and rename gitlogg-generate-log.sh?
- Currently, the path to read in is set via an environment variable. This is a bit awkward. Also, 99.9% of other programs would use a program argument for that. With 99d58d3, I introduced the possibility to parse command line arguments in gitlogg. Should we switch to that?

If you think this is helpful, I am more than happy to implement both these changes :-)

**Comment by dreamyguy** [comment]
@Inventitech feel free to rename *gitlogg-generate-log.sh* to *gitlogg.sh*. I kept it separated in case something else would turn out, but it never did. This has always been overkill.

Clarity around setup and process, which was my main concern, has become less painful with the [setup](https://github.com/dreamyguy/gitlogg/blob/abca3584cf053fd91aaafc5f74c9b332bcc2dd94/package.json#L30) script.

I'm fine with passing the path as an argument but would prefer that the environment variable would remain available as default (if there's no path argument, use the var). That way one can "set and forget".

I'll be more away on December, but will of course check for issues/PRs sporadically. 👍

**Comment by Inventitech** [comment]
Any progress on this? :)

**Comment by dreamyguy** [comment]
Right.. So I'm finally revisiting some projects. There's never enough time... ⌛️ 

I've decided to "discontinue" the `bash` implementation and focus on getting the `javascript` branch to a state where I can publish it as the main branch. That would overwrite this change, so there wouldn't be a point in merging it.

The only thing that kept me from merging it back then, when the PR was made, was that I would have to update the documentation. It required a very minor change but I couldn't prioritize even that.

Sometimes life takes over in overwhelming ways... 🌊
