### ISSUE TITLE
Git notes

### ISSUE THREAD

**Issue by Mihailoff** [dreamyguy/gitlogg#5]
Is there a way to include https://git-scm.com/docs/git-notes into resulting json? If you run `git log --show-notes=name-of-your-notes` you'll get some extra information.

```
commit 2e711912549af4efb9d1a8d13f6e325fefbc8a0e
Author: George Mihailov <george@example.com>
Date:   Wed Jun 8 11:33:07 2016 -0700

    Minor improvements

Notes (name-of-your-notes):
    Here are some notes about the commit

```

**Comment by dreamyguy** [comment]
I'll look into it. There's the `%N` pretty format placeholder for _commit notes_, which is already being used in the script. It should be relatively easy to include it, once it is sanitised.

**Comment by dreamyguy** [comment]
@Mihailoff you're in luck!

It so happens that **commit notes** is already available, it's just that it's [commented out on this line](https://github.com/dreamyguy/gitlogg/blob/master/gitlogg/gitlogg-parse-json.js#L113). There are other things commented out as well - a total of 23, as you can see further down on the [`gitlogg-parse-json.js`](https://github.com/dreamyguy/gitlogg/blob/master/gitlogg/gitlogg-parse-json.js) file. 💰 

Uncomment the ones you'd like to output and you're covered.
